name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-*"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Lint
        working-directory: frontend
        run: npm run lint --if-present

      - name: Type check
        working-directory: frontend
        run: npm run typecheck --if-present

      - name: Unit tests
        working-directory: frontend
        run: npm test --if-present -- --ci --watch=false

      - name: Build
        working-directory: frontend
        run: npm run build --if-present

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/dist
            frontend/.next
          if-no-files-found: ignore